services:
  app:
    build: .
    container_name: network-device-monitor
    command: gunicorn app:app --worker-class eventlet -w 1 --bind 0.0.0.0:8000 --reload --reload-extra-file ./templates/status.html
    ports:
      - "80:8000"
    volumes:
      - .:/app